---@class wibox.container
---@field arcchart wibox.container.arcchart
---@field background wibox.container.background
---@field constraint wibox.container.constraint
---@field margin wibox.container.margin
---@field mirror wibox.container.mirror
---@field place wibox.container.place
---@field radialprogressbar wibox.container.radialprogressbar
---@field rotate wibox.container.rotate
---@field scroll wibox.container.scroll
---@field tile wibox.container.tile
local cls = {}
