local menu_parts = {}

menu_parts["Archlinux"] = {
	{"AUR", "xdg-open https://aur.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
	{"Bugs", "xdg-open https://bugs.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
	{"Developers", "xdg-open http://www.archlinux.org/developers/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
	{"Documentation", "xdg-open https://wiki.archlinux.org/index.php/Official_Arch_Linux_Install_Guide", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
	{"Donate", "xdg-open http://www.archlinux.org/donate/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
	{"Forum", "xdg-open https://bbs.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
	{"Homepage", "xdg-open http://www.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
	{"SVN", "xdg-open http://projects.archlinux.org/svntogit/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
	{"Schwag", "xdg-open http://www.zazzle.com/archlinux/", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
	{"Wiki", "xdg-open https://wiki.archlinux.org", "/usr/share/icons/hicolor/32x32/apps/arch-logo.png" },
}

menu_parts["Barrierefreiheit"] = {
	{"Onboard", "onboard", "/usr/share/icons/hicolor/16x16/apps/onboard.png" },
}

menu_parts["Bildung"] = {
	{"GeoGebra", "geogebra"},
	{"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
}

menu_parts["Büro"] = {
	{"Dokumentenbetrachter", "evince "},
	{"Kalender", "gnome-calendar "},
	{"Kontakte", "gnome-contacts"},
	{"LibreOffice", "libreoffice ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-startcenter.png" },
	{"LibreOffice Base", "libreoffice --base ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-base.png" },
	{"LibreOffice Calc", "libreoffice --calc ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-calc.png" },
	{"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
	{"LibreOffice Impress", "libreoffice --impress ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-impress.png" },
	{"LibreOffice Math", "libreoffice --math ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-math.png" },
	{"LibreOffice Writer", "libreoffice --writer ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-writer.png" },
	{"MarkText", "/usr/lib/marktext/marktext ", "/usr/share/icons/hicolor/16x16/apps/marktext.png" },
	{"Minder", "com.github.phase1geo.minder ", "/usr/share/icons/hicolor/16x16/apps/com.github.phase1geo.minder.svg" },
	{"Wörterbuch", "xfce4-dict", "/usr/share/icons/hicolor/16x16/apps/org.xfce.Dictionary.png" },
}

menu_parts["Entwicklung"] = {
	{"CMake", "cmake-gui ", "/usr/share/icons/hicolor/32x32/apps/CMakeSetup.png" },
	{"Code - OSS", "/usr/bin/code-oss --unity-launch ", "/usr/share/pixmaps/com.visualstudio.code.oss.png" },
	{"Cuttlefish", "cuttlefish"},
	{"D-Feet", "d-feet"},
	{"Devhelp", "devhelp"},
	{"Electron", "electron ", "/usr/share/pixmaps/electron.png" },
	{"Electron 13", "electron13 ", "/usr/share/pixmaps/electron13.png" },
	{"Electron 18", "electron18 ", "/usr/share/pixmaps/electron18.png" },
	{"Electron 19", "electron19 ", "/usr/share/pixmaps/electron19.png" },
	{"Eyedropper", "/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=eyedropper com.github.finefindus.eyedropper"},
	{"FLUID", "fluid ", "/usr/share/icons/hicolor/32x32/apps/fluid.png" },
	{"GdaBrowser", "gda-browser-5.0", "/usr/share/pixmaps/gda-browser-5.0.png" },
	{"Glade", "glade "},
	{"Globaler Plasma-Designexplorer", "lookandfeelexplorer"},
	{"Icon Browser", "yad-icon-browser", "/usr/share/icons/hicolor/16x16/apps/yad.png" },
	{"IntelliJ IDEA Community Edition", "/usr/bin/idea ", "/usr/share/pixmaps/idea.png" },
	{"Kate", "kate -b ", "/usr/share/icons/hicolor/16x16/apps/kate.png" },
	{"Lite XL", "lite-xl "},
	{"Micro", "xterm -e micro "},
	{"Minder", "com.github.phase1geo.minder ", "/usr/share/icons/hicolor/16x16/apps/com.github.phase1geo.minder.svg" },
	{"Plasma-Datenquellen-Betrachter", "plasmaengineexplorer"},
	{"Plasma-Designexplorer", "plasmathemeexplorer"},
	{"PyCharm Community Edition", "/usr/bin/pycharm ", "/usr/share/pixmaps/pycharm.png" },
	{"Qt Assistant", "assistant", "/usr/share/icons/hicolor/32x32/apps/assistant.png" },
	{"Qt Designer", "designer ", "/usr/share/icons/hicolor/128x128/apps/QtProject-designer.png" },
	{"Qt Linguist", "linguist ", "/usr/share/icons/hicolor/16x16/apps/linguist.png" },
	{"Qt QDBusViewer ", "qdbusviewer", "/usr/share/icons/hicolor/32x32/apps/qdbusviewer.png" },
	{"Sysprof", "sysprof "},
	{"Unity Hub", "/opt/unityhub/unityhub ", "/usr/share/icons/hicolor/16x16/apps/unityhub.png" },
	{"UserFeedback-Konsole", "UserFeedbackConsole"},
	{"ipython", "xterm -e ipython", "/usr/share/pixmaps/ipython.png" },
}

menu_parts["Grafik"] = {
	{"Adobe Flash Player Standalone", "/usr/bin/flashplayer"},
	{"Bildbetrachter", "gpicview ", "/usr/share/icons/hicolor/48x48/apps/gpicview.png" },
	{"Bildbetrachter", "eog "},
	{"Blender", "blender "},
	{"Dokument-Scanner", "simple-scan"},
	{"Dokumentenbetrachter", "evince "},
	{"Eyedropper", "/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=eyedropper com.github.finefindus.eyedropper"},
	{"Flameshot", "/usr/bin/flameshot", "/usr/share/icons/hicolor/48x48/apps/org.flameshot.Flameshot.png" },
	{"Fotos", "gnome-photos"},
	{"GNU Image Manipulation Program", "gimp-2.10 ", "/usr/share/icons/hicolor/16x16/apps/gimp.png" },
	{"Gpick", "gpick ", "/usr/share/icons/hicolor/48x48/apps/gpick.png" },
	{"Inkscape", "inkscape ", "/usr/share/icons/hicolor/16x16/apps/org.inkscape.Inkscape.png" },
	{"Krita", "krita ", "/usr/share/icons/hicolor/16x16/apps/krita.png" },
	{"LXImage", "lximage-qt ", "/usr/share/icons/hicolor/48x48/apps/lximage-qt.png" },
	{"LibreOffice Draw", "libreoffice --draw ", "/usr/share/icons/hicolor/16x16/apps/libreoffice-draw.png" },
	{"Ristretto-Bildbetrachter", "ristretto ", "/usr/share/icons/hicolor/16x16/apps/org.xfce.ristretto.png" },
	{"ScreenGrab", "screengrab"},
	{"XDvi", "xdvi "},
	{"gThumb", "gthumb ", "/usr/share/icons/hicolor/16x16/apps/org.gnome.gThumb.png" },
}

menu_parts["Internet"] = {
	{"Avahi SSH-Server-Browser", "/usr/bin/bssh"},
	{"Avahi VNC-Server-Browser", "/usr/bin/bvnc"},
	{"Brave", "brave ", "/usr/share/icons/hicolor/16x16/apps/brave-desktop.png" },
	{"Discord", "/usr/bin/discord", "/usr/share/pixmaps/discord.png" },
	{"Ein verbundenes mit KDE Connect öffnen", "kdeconnect-handler --open "},
	{"FileZilla", "filezilla", "/usr/share/icons/hicolor/16x16/apps/filezilla.png" },
	{"Firefox", "/usr/lib/firefox/firefox ", "/usr/share/icons/hicolor/16x16/apps/firefox.png" },
	{"Google Chrome", "/usr/bin/google-chrome-stable ", "/usr/share/icons/hicolor/16x16/apps/google-chrome.png" },
	{"HakuNeko Desktop", "/usr/lib/hakuneko-desktop/hakuneko", "/usr/share/icons/hicolor/16x16/apps/hakuneko-desktop.png" },
	{"HexChat", "hexchat --existing ", "/usr/share/icons/hicolor/48x48/apps/io.github.Hexchat.png" },
	{"KDE Connect", "kdeconnect-app"},
	{"KDE Connect-SMS", "kdeconnect-sms"},
	{"KDE-Connect-Anzeige", "kdeconnect-indicator"},
	{"Steam (Native)", "/usr/bin/steam-native ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
	{"Steam (Runtime)", "/usr/bin/steam-runtime ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
	{"TeamViewer", "/opt/teamviewer/tv_bin/script/teamviewer", "/usr/share/icons/hicolor/16x16/apps/TeamViewer.png" },
	{"TigerVNC-Betrachter", "/usr/bin/vncviewer", "/usr/share/icons/hicolor/16x16/apps/tigervnc.png" },
	{"Transmission", "transmission-gtk ", "/usr/share/pixmaps/transmission.png" },
	{"Verbindungen", "gnome-connections "},
	{"Web", "epiphany "},
}

menu_parts["Spiele"] = {
	{"Dosbox", "dosbox", "/usr/share/pixmaps/dosbox.png" },
	{"Flashpoint Infinity", "/usr/lib/flashpoint-infinity/flashpoint-launcher ", "/usr/share/icons/hicolor/16x16/apps/flashpoint-launcher.png" },
	{"Lutris", "lutris ", "/usr/share/icons/hicolor/16x16/apps/lutris.png" },
	{"Mesen-S", "/usr/bin/mesen-s", "/usr/share/pixmaps/Mesen-S.png" },
	{"Mindustry", "/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=mindustry.sh com.github.Anuken.Mindustry"},
	{"Minecraft Launcher", "minecraft-launcher"},
	{"PolyMC", "polymc"},
	{"Powder Toy", "/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=powder uk.co.powdertoy.tpt", "/var/lib/flatpak/exports/share/icons/hicolor/16x16/apps/uk.co.powdertoy.tpt.png" },
	{"RetroArch", "retroarch", "/usr/share/pixmaps/retroarch.svg" },
	{"Steam (Native)", "/usr/bin/steam-native ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
	{"Steam (Runtime)", "/usr/bin/steam-runtime ", "/usr/share/icons/hicolor/16x16/apps/steam.png" },
	{"mGBA", "mgba-qt ", "/usr/share/pixmaps/mgba.png" },
}

menu_parts["Systemwerkzeuge"] = {
	{"Alacritty", "alacritty", "/usr/share/pixmaps/Alacritty.svg" },
	{"Android File Transfer (MTP)", "android-file-transfer"},
	{"Avahi Zeroconf Browser", "/usr/bin/avahi-discover"},
	{"Crashed Processes Viewer", "drkonqi-coredump-gui"},
	{"Discover", "plasma-discover ", "/usr/share/icons/hicolor/16x16/apps/plasmadiscover.png" },
	{"Dolphin", "dolphin "},
	{"Druckerverwaltung", "/usr/bin/xdg-open http://localhost:631/", "/usr/share/icons/hicolor/16x16/apps/cups.png" },
	{"Festplattenbelegungsanalyse", "baobab "},
	{"GParted", "/usr/bin/gparted ", "/usr/share/icons/hicolor/16x16/apps/gparted.png" },
	{"Hardware Locality lstopo", "lstopo"},
	{"Htop", "xterm -e htop", "/usr/share/pixmaps/htop.png" },
	{"KDE-Partitionsverwaltung", "partitionmanager"},
	{"KSysGuard", "ksysguard "},
	{"Konsole", "konsole"},
	{"LSHW", "/usr/sbin/gtk-lshw", "///usr/share/lshw/artwork/logo.svg" },
	{"LXTerminal", "lxterminal", "/usr/share/icons/hicolor/128x128/apps/lxterminal.png" },
	{"Massenumbenennen", "thunar --bulk-rename ", "/usr/share/icons/hicolor/16x16/apps/org.xfce.thunar.png" },
	{"OpenJDK Java 11 Console", "/usr/lib/jvm/java-11-openjdk/bin/jconsole", "/usr/share/icons/hicolor/16x16/apps/java11-openjdk.png" },
	{"OpenJDK Java 11 Shell", "xterm -e /usr/lib/jvm/java-11-openjdk/bin/jshell", "/usr/share/icons/hicolor/16x16/apps/java11-openjdk.png" },
	{"Oracle VM VirtualBox", "VirtualBox ", "/usr/share/icons/hicolor/16x16/mimetypes/virtualbox.png" },
	{"PCManFM Dateimanager", "pcmanfm "},
	{"Paketaktualisierung", "gpk-update-viewer"},
	{"Pakete", "gpk-application"},
	{"Protokolle", "gnome-logs"},
	{"QTerminal", "qterminal"},
	{"QTerminal herabhängend", "qterminal --drop"},
	{"Sensorbetrachter", "xfce4-sensors", "/usr/share/icons/hicolor/24x24/apps/xfce-sensors.png" },
	{"Software", "gnome-software "},
	{"Systemmonitor", "plasma-systemmonitor"},
	{"Systemüberwachung", "gnome-system-monitor"},
	{"Taskmanager", "lxtask"},
	{"Taskmanager", "xfce4-taskmanager", "/usr/share/icons/hicolor/16x16/apps/org.xfce.taskmanager.png" },
	{"Terminal", "gnome-terminal"},
	{"Thunar-Dateiverwaltung", "thunar ", "/usr/share/icons/hicolor/16x16/apps/org.xfce.thunar.png" },
	{"Tilix", "tilix"},
	{"Tint2", "tint2"},
	{"UXTerm", "uxterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
	{"VMware Player", "/usr/bin/vmplayer ", "/usr/share/icons/hicolor/16x16/apps/vmware-player.png" },
	{"VMware Workstation", "/usr/bin/vmware ", "/usr/share/icons/hicolor/16x16/apps/vmware-workstation.png" },
	{"Vala Panel", "vala-panel"},
	{"Virtual Network Editor", "/usr/bin/vmware-netcfg", "/usr/share/icons/hicolor/16x16/apps/vmware-netcfg.png" },
	{"Virtuelle Maschinenverwaltung", "virt-manager", "/usr/share/icons/hicolor/16x16/apps/virt-manager.png" },
	{"WezTerm", "wezterm start --cwd . --", "/usr/share/icons/hicolor/128x128/apps/org.wezfurlong.wezterm.png" },
	{"XTerm", "xterm", "/usr/share/pixmaps/xterm-color_48x48.xpm" },
	{"Xfce-Terminal", "xfce4-terminal", "/usr/share/icons/hicolor/16x16/apps/org.xfce.terminal.png" },
	{"dconf-Editor", "dconf-editor"},
	{"gmrun", "gmrun", "/usr/share/pixmaps/gmrun.png" },
	{"kitty", "kitty", "/usr/share/icons/hicolor/256x256/apps/kitty.png" },
	{"nnn", "xterm -e nnn", "/usr/share/icons/hicolor/64x64/apps/nnn.png" },
}

menu_parts["Unterhaltungsmedien"] = {
	{"Adobe Flash Player Standalone", "/usr/bin/flashplayer"},
	{"Cheese", "cheese"},
	{"EasyTAG", "easytag ", "/usr/share/icons/hicolor/16x16/apps/easytag.png" },
	{"Echomixer", "echomixer", "/usr/share/icons/hicolor/48x48/apps/echomixer.png" },
	{"Envy24 Control", "envy24control", "/usr/share/icons/hicolor/48x48/apps/envy24control.png" },
	{"HDAJackRetask", "hdajackretask"},
	{"HDSPConf", "hdspconf", "/usr/share/icons/hicolor/48x48/apps/hdspconf.png" },
	{"HDSPMixer", "hdspmixer", "/usr/share/icons/hicolor/48x48/apps/hdspmixer.png" },
	{"Hwmixvolume", "hwmixvolume", "/usr/share/icons/hicolor/48x48/apps/hwmixvolume.png" },
	{"Jellyfin Media Player", "jellyfinmediaplayer"},
	{"Kdenlive", "kdenlive ", "/usr/share/icons/hicolor/16x16/apps/kdenlive.png" },
	{"Kodi", "kodi", "/usr/share/icons/hicolor/16x16/apps/kodi.png" },
	{"Kwave-Sound-Editor", "kwave "},
	{"LXMusic simple music player", "lxmusic", "/usr/share/icons/hicolor/128x128/apps/lxmusic.png" },
	{"MakeMKV", "makemkv", "/usr/share/icons/hicolor/16x16/apps/makemkv.png" },
	{"Musik", "gnome-music"},
	{"New Session Manager (Legacy GUI)", "nsm-legacy-gui"},
	{"OBS Studio", "obs", "/usr/share/icons/hicolor/128x128/apps/com.obsproject.Studio.png" },
	{"OSD Lyrics", "osdlyrics", "/usr/share/icons/hicolor/64x64/apps/osdlyrics.png" },
	{"OpenShot Video Editor", "openshot-qt ", "/usr/share/icons/hicolor/64x64/apps/openshot-qt.png" },
	{"Parole-Medienspieler", "parole ", "/usr/share/icons/hicolor/16x16/apps/org.xfce.parole.png" },
	{"PulseAudio Equalizer", "pulseaudio-equalizer-gtk"},
	{"PulseAudio System Tray", "pasystray", "/usr/share/pixmaps/pasystray.png" },
	{"PulseAudio Volume Control", "pavucontrol-qt"},
	{"PulseAudio-Lautstärkeregler", "pavucontrol"},
	{"Qt V4L2 test Utility", "qv4l2", "/usr/share/icons/hicolor/16x16/apps/qv4l2.png" },
	{"Qt V4L2 video capture utility", "qvidcap", "/usr/share/icons/hicolor/16x16/apps/qvidcap.png" },
	{"Shotcut", "shotcut ", "/usr/share/icons/hicolor/64x64/apps/org.shotcut.Shotcut.png" },
	{"SimpleScreenRecorder", "simplescreenrecorder --logfile", "/usr/share/icons/hicolor/16x16/apps/simplescreenrecorder.png" },
	{"Sonixd", "sonixd", "/usr/share/pixmaps/sonixd.png" },
	{"Soundux", "/opt/soundux/soundux", "/usr/share/pixmaps/soundux.png" },
	{"Spek", "spek ", "/usr/share/icons/hicolor/16x16/apps/spek.png" },
	{"Tonaufzeichner", "gnome-sound-recorder"},
	{"VLC Media Player", "/usr/bin/vlc --started-from-file ", "/usr/share/icons/hicolor/16x16/apps/vlc.png" },
	{"Videos", "totem "},
	{"Volume Icon", "volumeicon"},
	{"Xfburn", "xfburn"},
	{"mpv Media Player", "mpv --player-operation-mode=pseudo-gui -- ", "/usr/share/icons/hicolor/16x16/apps/mpv.png" },
}

menu_parts["Zubehör"] = {
	{"Anwendungsfinder", "xfce4-appfinder", "/usr/share/icons/hicolor/16x16/apps/org.xfce.appfinder.png" },
	{"Archivverwaltung", "file-roller "},
	{"Azote", "azote", "/usr/share/pixmaps/azote.svg" },
	{"Barrier", "barrier"},
	{"Bildbetrachter", "gpicview ", "/usr/share/icons/hicolor/48x48/apps/gpicview.png" },
	{"Bildschirmfoto", "gnome-screenshot --interactive"},
	{"Bildschirmfoto", "xfce4-screenshooter", "/usr/share/icons/hicolor/16x16/apps/org.xfce.screenshooter.png" },
	{"Bücher", "gnome-books"},
	{"Dateien", "nautilus --new-window "},
	{"Erweiterungen", "/usr/bin/gnome-extensions-app --gapplication-service"},
	{"Eyedropper", "/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=eyedropper com.github.finefindus.eyedropper"},
	{"Hilfe", "yelp "},
	{"Icon picker", "nwg-icon-picker", "/usr/share/pixmaps/nwg-icon-picker.svg" },
	{"KCalc", "kcalc"},
	{"KWrite", "kwrite ", "/usr/share/icons/hicolor/16x16/apps/kwrite.png" },
	{"Karten", "gapplication launch org.gnome.Maps "},
	{"Kate", "kate -b ", "/usr/share/icons/hicolor/16x16/apps/kate.png" },
	{"Klipper", "klipper"},
	{"Kupfer", "kupfer ", "/usr/share/icons/hicolor/22x22/apps/kupfer.png" },
	{"Kvantum Manager", "kvantummanager"},
	{"LXQt Archiver", "lxqt-archiver "},
	{"Latte", "/usr/bin/latte-dock", "/usr/share/icons/hicolor/16x16/apps/latte-dock.svg" },
	{"Laufwerke", "gnome-disks"},
	{"Launchy", "launchy ", "/usr/share/pixmaps/launchy_icon.png" },
	{"MarkText", "/usr/lib/marktext/marktext ", "/usr/share/icons/hicolor/16x16/apps/marktext.png" },
	{"Marker", "marker "},
	{"Micro", "xterm -e micro "},
	{"Minder", "com.github.phase1geo.minder ", "/usr/share/icons/hicolor/16x16/apps/com.github.phase1geo.minder.svg" },
	{"Mousepad", "mousepad ", "/usr/share/icons/hicolor/16x16/apps/org.xfce.mousepad.png" },
	{"Nextcloud Desktop-Synchronisationsclient", "nextcloud ", "/usr/share/icons/hicolor/16x16/apps/Nextcloud.png" },
	{"Notizen", "xfce4-notes", "/usr/share/icons/hicolor/16x16/apps/xfce4-notes-plugin.png" },
	{"Onboard", "onboard", "/usr/share/icons/hicolor/16x16/apps/onboard.png" },
	{"Optimierungen", "gnome-tweaks"},
	{"PCManFM-Qt", "pcmanfm-qt "},
	{"Plank", "plank", "/usr/share/icons/hicolor/16x16/apps/plank.svg" },
	{"Redshift", "redshift-gtk"},
	{"Schriften", "gnome-font-viewer "},
	{"Taschenrechner", "gnome-calculator"},
	{"Uhren", "gnome-clocks"},
	{"Ulauncher", "env GDK_BACKEND=x11 /usr/bin/ulauncher --hide-window", "/usr/share/icons/hicolor/48x48/apps/ulauncher.svg" },
	{"Verbindungen", "gnome-connections "},
	{"Vim", "xterm -e vim ", "/usr/share/icons/hicolor/48x48/apps/gvim.png" },
	{"Wetter", "gapplication launch org.gnome.Weather"},
	{"Winetricks", "winetricks --gui"},
	{"Xarchiver", "xarchiver ", "/usr/share/icons/hicolor/16x16/apps/xarchiver.png" },
	{"Xfburn", "xfburn"},
	{"Youtube Downloader Plus", "/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=run.sh me.aandrew.ytdownloader", "/var/lib/flatpak/exports/share/icons/hicolor/64x64/apps/me.aandrew.ytdownloader.png" },
	{"Zeichen", "/usr/bin/gnome-characters"},
	{"Zeichentabelle", "gucharmap"},
	{"Zwischenablageverwaltung", "xfce4-clipman", "/usr/share/icons/hicolor/16x16/apps/xfce4-clipman-plugin.png" },
	{"gedit", "gedit "},
	{"ipython", "xterm -e ipython", "/usr/share/pixmaps/ipython.png" },
	{"nitrogen", "nitrogen", "/usr/share/icons/hicolor/16x16/apps/nitrogen.png" },
	{"pentablet", "/usr/lib/pentablet/pentablet.sh", "///usr/share/icons/pentablet.png" },
	{"picom", "picom"},
}

local xdg_menu = {
	{"Archlinux", menu_parts["Archlinux"]},
	{"Barrierefreiheit", menu_parts["Barrierefreiheit"]},
	{"Bildung", menu_parts["Bildung"]},
	{"Büro", menu_parts["Büro"]},
	{"Entwicklung", menu_parts["Entwicklung"]},
	{"Grafik", menu_parts["Grafik"]},
	{"Internet", menu_parts["Internet"]},
	{"Spiele", menu_parts["Spiele"]},
	{"Systemwerkzeuge", menu_parts["Systemwerkzeuge"]},
	{"Unterhaltungsmedien", menu_parts["Unterhaltungsmedien"]},
	{"Zubehör", menu_parts["Zubehör"]},
}

return xdg_menu
